### ISSUE TITLE
'trust data has invalid format.'

### ISSUE THREAD

**Issue by kevinchcn** [sse-secure-systems/connaisseur#10]
I am using Dockerhub instead of Harbor and getting the following error:
`Error from server: error when creating "deploymentandservice.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: trust data has invalid format.`
Below is the connaisseur pod log:
`[2020-09-30 00:59:37,182] ERROR: {'message': 'trust data has invalid format.', 'context': {'trust_data_type': 'root', 'user': 'minikube-user', 'operation': 'CREATE', 'kind': 'Deployment', 'namespace': 'default', 'name': 'sample-deployment', 'image': '272965041/signed-image:v1'}, 'detection_mode': False}`

**Comment by xopham** [comment]
Thanks for the feedback @kevinchcn ! Such feedback is very valuable to us :+1: 
We are using json schema to validate the trust data and it seems that the validation pattern for the expiry date in [targets_schema.json](https://github.com/sse-secure-systems/connaisseur/blob/master/connaisseur/res/targets_schema.json#L15) is not compatible with negative time zones. We are working on a PR and hope to fix the issue soon.

**Comment by annekebr** [comment]
Hey @kevinchcn! Again, thanks a lot for your feedback! 

We will fix the trust data validation with the merge of the above mentioned PR, closing this issue automatically - in case you still face any issues with the upcoming `v1.1.3` version feel free to reopen!

**Comment by kevinchcn** [comment]
It works now.
Thanks for the help everybody!  You all are rockstars!
