### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by phbelitz** [sse-secure-systems/connaisseur#105]
**Describe the feature**
We need a pull request template, so that it automatically creates them for the `develop` branch, and NOT the `master` branch.

**Comment by peterthomassen** [comment]
I believe this is not a question of templates, but rather of what's the repository's default branch. See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository

**Comment by xopham** [comment]
Closed. Can be fixed when necessary.
