### ISSUE TITLE
Deployment on Production Environment

### ISSUE THREAD

**Issue by aalapv** [sse-secure-systems/connaisseur#11]
Looking at the pod logs of Connaisseur during testing, it gives a warning related to the Flask server mentioning that a production WSGI should be used:

```
 * Serving Flask app "connaisseur.flask_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
```

I went through the Connaisseur documentation to find out how it could be deployed on a production environment, but could not find anything related. 

Could you please mention what is the right way to deploy Connaisseur on a production environment (EKS)?

**Comment by phbelitz** [comment]
Thank you for your input @aalapv. As you already noticed, we are using Flask to serve out connaisseur application and according to the [flask documentation](https://werkzeug.palletsprojects.com/en/1.0.x/serving/), the server itself is not production ready, as it performs poorly under high load. For now we decided that this is not a major issue, as in the general use cases connaisseur won't be bombarded with request, so you can go ahead and use it. However should you expect connaisseur to be taking a ton of request in your specific cluster and experience issues with the load, we'd be very interested to hearing more about it.

We plan on tackeling this issue further down the road.
