### ISSUE TITLE
Reduce code repetition in Github Actions

### ISSUE THREAD

**Issue by Starkteetje** [sse-secure-systems/connaisseur#112]
**Describe the feature**
We have a lot of code duplication in Github Actions, especially with regards to the integration tests, that are run for both CICD and Release workflows and where both namespaced and "basic" integration test are very similar to each other

**Optional: Implementation ideas**
Github has the [workflow_run](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) option that would allow triggering an integration test workflow from both CICD and Release, but probably the workflow result would not be shown as part of the workflow, i.e. one has CICD running due to a PR, CICD triggers integration tests, then shows green checkmark regardless of whether integration test workflow succeeded or failed. <- All that's only theory, I didn't test it

**Comment by annekebr** [comment]
Oh, seems I forgot to close this issue. I think #145 closed this issue, so closing now.
