### ISSUE TITLE
Consider setting a codecov yaml to e.g. enforce minimum coverage...

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#118]
**Describe the feature**
A minimum code coverage via codecov yaml could be enforced: https://docs.codecov.io/docs/codecov-yaml

**Comment by Starkteetje** [comment]
At least the base implementation of it needs the codecov app, which we don't want to use given the recent breach; we could also write our own interpreter of the test coverage file, but that seems to be too much work for not enough gain atm
