### ISSUE TITLE
More logging around cosign signature verification

### ISSUE THREAD

**Issue by dbbhat** [sse-secure-systems/connaisseur#1236]
**Describe the bug**
We are observing that Connaisseur is intermittently taking too long to verify signatures and doesn't respond within the timeout of 30s. On enabling debug logs we see that it's the cosign process that is taking longest duration to return from a successful verification. For example 

```
{"timestamp": "2023-09-13 22:20:47.049919", "message": "", "kind": "AdmissionReview", "apiVersion": 
<...>

{"timestamp": "2023-09-13 22:20:47.057010", "message": "starting verification of image \"<image-name>:<tag>\" using rule \"<foo-rule>\" with arguments {'threshold': 1, 'trustRoot': '*', 'verifyInTransparencyLog': False} and validator \"cosignvalidator\".", "policy_rule": "<foo-rule>", "validator": "cosignvalidator", "admission_review": {"user": "system:serviceaccount:flux-system:helm-controller", "operation": "UPDATE", "kind": "Deployment", "name": "<foo-deployment>", "namespace": "<foo-ns>"}, "image": "<image-name>:<tag>"}

{"timestamp": "2023-09-13 22:20:56.644393", "message": "COSIGN output of trust root '<key-1>' for image'<image-name>:<tag>': RETURNCODE: 0; STDOUT: {\"critical\":{\"identity\":{\"docker-reference\":\"<image-name>\"},\"image\":{\"docker-manifest-digest\":\"sha256:<digest>\"},\"type\":\"cosign container image 

{"timestamp": "2023-09-13 22:20:59.507098", "message": "COSIGN output of trust root '<key-2>' for image'<image-name>:<tag>': RETURNCODE: 0; STDOUT: {\"critical\":{\"identity\":{\"docker-reference\":\"<image-name>\"},\"image\":{\"docker-manifest-digest\":\"sha256:<digest>\"},\"type\":\"cosign container image 

{"timestamp": "2023-09-13 22:20:59.507527", "message": "successful verification of image \"<image-name>:<tag>\"", "admission_review": {"user": "system:serviceaccount:flux-system:helm-controller", "operation": "UPDATE", "kind": "Deployment", "name": "<foo-deployment>", "namespace": "<foo-ns>"}, "image": "<image-name>:<tag>"}
```

Observe that the verification begins almost immediately after Connaisseur receives the request but to return from `cosign` verify process, it takes almost 10 seconds. Even with `debug` logs enabled, we have no visibility into why it takes so long to verify the signature. There should be more logging around the individual steps done in `cosign verify` process (contacting the registry, verification with trust roots etc.) so that users know where the problem is. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>

**Optional: Versions (please complete the following information as relevant):**
 - Kubernetes Cluster: v1.26
 - Connaisseur: v3.0.0

**Comment by Starkteetje** [comment]
I've adapted the call to Cosign such that if Connaisseur is running in debug mode, we'll also call Cosign with `--verbose`, which should somewhat increase visibility. I don't think it gets much better than that since we're calling the Cosign binary as an opaque blob and just get whatever comes out, so also don't get too much information
