### ISSUE TITLE
Option for HTML escaping of alert messages

### ISSUE THREAD

**Issue by Starkteetje** [sse-secure-systems/connaisseur#1518]
**Describe the feature**
It would be nice have a flag to enable HTML escapes for alerts. While alert output is JSON, receivers are likely to show the output in a website, e.g. Slack. Most receivers know to handle unsafe HTML from webhooks, e.g. disallow Javascript, but it would be good to at least allow the option to escape these values as with Connaisseur's thread model they include attacker-controlled values such as image names or (parts of) failure messages, which could be used to attack users' alert handling infrastructure.

**Comment by peterthomassen** [comment]
Is this common for such tooling? It seems to me to be entirely out of scope, and adding complexity which always comes with cost.

**Comment by Starkteetje** [comment]
You're right. It does not seem to be common and the idea was born from being implemented accidentally instead of from an actual need. Will close
