### ISSUE TITLE
Does Connaisseur have caching mechanism that prevents repeat verification of an image?

### ISSUE THREAD

**Issue by qx121** [sse-secure-systems/connaisseur#1536]
**Describe the feature**
Our environment requires to create/delete lots of pods with same image. It pressures our internal registry as each pod image verification request reaches container registry.

If there is a cache mechanism such that connaisseur automatically approves images that have been previously verified, it would largely reduce registry's pressure and verification latency of pods.

**Optional: Is your feature request related to a problem? Please describe.**
<A clear and concise description of what the problem is.>

**Optional: Implementation ideas**
<Maybe you already have an implementation and alternatives in mind. Please share your thoughts.>
I think it is doable to implement an in-memory cache. When a verification request comes in, check whether the image is in the cache and auto-approve the in-cache image.

**Optional: Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by peterthomassen** [comment]
This will be part of the Golang rewrite, see https://github.com/sse-secure-systems/connaisseur/discussions/1513.

**Comment by qx121** [comment]
Thanks @peterthomassen! is there a roadmap for golang-rewrite being released?

**Comment by phbelitz** [comment]
@qx121 yes there is a roadmap and it says it's released at this very moment.

**Comment by peterthomassen** [comment]
I love how you do a language change in a minor release. :sunglasses:
