### ISSUE TITLE
rebuild validator health check

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#167]
**Describe the feature**
The validator health check should be reconsidered. It used to be called and logged when health probe is checked. This introduced an error and was for that reason removed: https://github.com/sse-secure-systems/connaisseur/pull/166

**Optional: Implementation ideas**
the health checks could run as a separate periodic probe, potentially in a separate container, or as a separate thread.

This might be a good chance to reconsider the liveliness and readiness probe altogether

**Comment by phbelitz** [comment]
its has been done to some extend ... readiness and liveness probe are equal.
