### ISSUE TITLE
Support ed25519 algorythm for verifying signed images with cosign

### ISSUE THREAD

**Issue by petr0ff** [sse-secure-systems/connaisseur#1691]
**Describe the feature**
Hello! For security reasons we have a requirement to use ed25519 hashing algorythm for signing keys for cosign'ed images. As I see, the current hash algorythm is hardcoded to SHA256. Is there any plans/comments for implementing this?

**Optional: Is your feature request related to a problem? Please describe.**
<A clear and concise description of what the problem is.>

**Optional: Implementation ideas**
The hashAlgorythm can be set for each trustRoot in values.yaml and then used in cosign_validator.go in func LoadKeyVerifierTuple, 

**Optional: Additional context**
<Add any other context or screenshots about the feature request here.>

**Comment by Starkteetje** [comment]
Hi @petr0ff 
Ed25519 is a **signing algorithm**, while SHA-256 is a **hashing** algorithm. These concepts interact, but aren't really related cryptographically. I'll assume you want to use the Ed25519 **signing algorithm**.

Generally, our choice of algorithms is bound by underlying signing systems, i.e. Notary and Cosign. As Connaisseur's mission is to bring verification from these systems into Kubernetes, we won't be going beyond what these signing systems offer.

That said, while Cosign explicitly and [intentionally uses ECDSA](https://github.com/sigstore/cosign?tab=readme-ov-file#intentionally-missing-features) for key generation, it does however [support more algorithms](https://github.com/sigstore/sigstore/blob/1bbe33108312349ecb12badff611f23c262c0760/pkg/signature/verifier.go#L49) during verification, in particular also Ed25519. While it is true that we currently hardcode SHA-256 as a hash algorithm, that value is not used by Cosign for Ed25519 as you can see [in the code](https://github.com/sigstore/sigstore/blob/1bbe33108312349ecb12badff611f23c262c0760/pkg/signature/verifier.go#L67-L72).

Consequently, Ed25519 verification with Connaisseur works. You can test this yourself. Try running Connaisseur with a cosign config and public key 
```
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAmh1UYbnDM9uBzZSFzwtxg/voRgaa631la1HT93z+PyE=
-----END PUBLIC KEY-----
```
which you can verify is an Ed25519 key using `openssl asn1parse --in <file with the above content>`.

Then configure a policy for image `teetje/tested25519` and `with.verifyInTransparencyLog: false` (signing with tlog gave me errors) and try running pods with images `teetje/tested25519:signed` and `teetje/tested25519:unsigned`, respectively. You'll see that the signed version goes through, while the unsigned one is blocked.

I hope that helps. Also, if you were discouraged by our docs saying we support only ECDSA and RSA, [I just fixed that](https://github.com/sse-secure-systems/connaisseur/pull/1698/commits/19f4cc7728069ac3bf144667430230757e3c1785) and the docs update will be live with our next release.

Kind regards

**Comment by petr0ff** [comment]
Hi, @Starkteetje ! Many thanks for your reply, indeed we tested it and didn't find any issues with signature verifying for images signed with ed25519, it just works :) and thanks for docs update!
