### ISSUE TITLE
Not able to Deploy Connaisseur 

### ISSUE THREAD

**Issue by sjain700** [sse-secure-systems/connaisseur#1802]
**Describe the bug**
Not able to deploy connaisseur

**Expected behavior**
The deployment should happen
NAME: connaisseur
LAST DEPLOYED: Fri Jul  9 20:43:10 2021
NAMESPACE: connaisseur
STATUS: deployed
REVISION: 1
TEST SUITE: None

**Optional: To reproduce**
I was trying out Connaisseur and just executed three command:
git clone https://github.com/sse-secure-systems/connaisseur.git
cd connaisseur
helm install connaisseur helm --atomic --create-namespace --namespace connaisseur

Its giving error:
Error: INSTALLATION FAILED: template: connaisseur/templates/secrets.yaml:3:41: executing "connaisseur/templates/secrets.yaml" at <.auth>: wrong type for value; expected map[string]interface {}; got interface {}

**Comment by Starkteetje** [comment]
Hi @sjain700 
that's pecuilar and shouldn't happen. I tried the installation on a fresh machine and it worked. Can you share details of your installation, e.g. the git commit hash, the helm version?
