### ISSUE TITLE
Add support for other key types of cosign

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#201]
**Describe the feature**
Cosign supports different types of keys than the standard ECDSA, but also RSA or certificate and keyless (also #141 ). 

**Optional: Is your feature request related to a problem? Please describe.**
It may make sense to find a general way to support these different types of keys.

**Optional: Implementation ideas**
configuration-wise the `.validators[*].trust_roots[*].type` key could be added with default ECDSA and then distinct handling of the received keys according to cosign docs.

**Comment by timothy-spencer** [comment]
We would love some action on this too!
