### ISSUE TITLE
Use Github's standardized code scanning interface for Actions

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#22]
Github provides [CodeQL](https://securitylab.github.com/tools/codeql) as a standardized interface to scanning code in the CI. This simplifies implementation and reporting. Several scanners are available on the [Marketplace](https://github.com/marketplace), e.g.:
- https://github.com/marketplace/actions/bandit-check
- https://github.com/marketplace/actions/aqua-security-trivy

This could be used to enhance the current CI and also add periodic scans.

**Comment by Starkteetje** [comment]
Given that the bandit check isnt too bad to do by oneself, would you really want to include some random's action in our pipeline? For trivy it's different, as their action is actually tied to their account

**Comment by xopham** [comment]
Advantage of using the standardized interface (that we could also connect our bandit to!) is the centralized vulnerability management. That might offer a handy solution to improve management of upcoming vulnerabilities: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-code-scanning-alerts-for-your-repository

Also we could easily test more of the scanners and other options from the marketplace the results: https://github.com/marketplace/category/security
