### ISSUE TITLE
EKS denies self signed certificate used by connaisseur

### ISSUE THREAD

**Issue by jackalsh** [sse-secure-systems/connaisseur#224]
**Describe the bug**
Connaisseur use TLS for mutation webhook endpoint. But first example you provide to validate installation fails:
`kubectl run demo --image=docker.io/securesystemsengineering/testimage:signed
Error from server (InternalError): Internal error occurred: failed calling webhook "connaisseur-svc.connaisseur.svc": Post "https://connaisseur-svc.connaisseur.svc:443/mutate?timeout=30s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "connaisseur-svc.connaisseur.svc")`

As I understand, this is because of self signed certificate. I didn't found any option to replace this certificate from values file? Looking inside the chart I see, that you generate self signed certificate for the service.

I am wondering how this is working for you on your Kubernetes cluster. I use EKS and control plane just deny this certificate.

**Expected behavior**
Certificate should be provided from values file or from predefined Secret. Provide an option to generate Self signed certificate only if no other option is provided.

**Optional: To reproduce**
I follow the official steps to install and validate connaisseur.

**Optional: Versions (please complete the following information as relevant):**
 - EKS 1.20

**Comment by xopham** [comment]
@jackalsh that is a good point. For local testing, minikube and microk8s are used. However, tests were run on several managed solutions as well, as described [in the docs](https://sse-secure-systems.github.io/connaisseur/v2.1.0/#compatibility). There was a change in how the cert is generated in the meantime. We'll have to look into that.
Still, making the cert configurable would be a good improvement. Flagging as `enhancement`.

**Comment by jackalsh** [comment]
I debugged this issue and have some results.

When you deploy chart for a first time, it works well.
You generate self signed certificate and generate 
* MutatingWebhookConfiguration connaisseur-webhook
* Secret connaisseur-tls
Both objects include same certificate for TLS validation inside the webhook mechanism. When you upgrade chart, for any reason, event without any additional changes, new certificate generated and all above objects updated with this new certificate. Webhook immediately starts to use this new certificate, but controller still uses old one(!!!). It cause all cluster behave unoperational, when each new pod fails to start with the 
`Error from server (InternalError): Internal error occurred: failed calling webhook "connaisseur-svc.connaisseur.svc": Post "https://connaisseur-svc.connaisseur.svc:443/mutate?timeout=30s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "connaisseur-svc.connaisseur.svc")`

It happens no matter what is the configuration of connaisseur, if detectionMode is enabled or not, because the above exception is coming from Kubernetes itself and not the controller service. More, when I try to restart the connaisseur to start using new certificates if also fails, because webhook denies it.
Using helm to uninstall service fails, because as I understand you use post hook to delete resources.

The only solution is to remove webhook manually and redeploy service
`
kubectl delete MutatingWebhookConfiguration connaisseur-webhook
kubectl delete APIService v1.connaisseur.policy
kubectl delete ClusterRole connaisseur-hook-role connaisseur-role
kubectl delete ClusterRoleBindings connaisseur-hook-rolebinding connaisseur-rolebinding
kubectl delete ns connaisseur
kubectl delete -f ./chart/crds/imagepolicy.yaml
`

Probably in your testing environment you deploy connaisseur in fresh minikube environment and never upgrade it in place.

**Comment by xopham** [comment]
We have actually come across this and already documented in issue #181 . Currently, we recommend to go for `helm uninstall`+`helm install` for upgrading, until we get this resolved.
Ultimately, it results from the fact that the order is crucial for Connaisseur administration operations, as one otherwise might run into a state where the webhook blocks as it cannot reach an already terminated service.

**Comment by xopham** [comment]
Will close this issue in favor of #181 . Feel free to re-open if that seems unfit.
