### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by Starkteetje** [sse-secure-systems/connaisseur#25]
Would be nice if we had an integration test of at least roughly the setup guide. If it ran inside the pipeline that would be best, however as a start, local test script may be sufficient

**Comment by xopham** [comment]
To run integration tests fast, one could use one of the lightweight solutions:
- k3s: https://github.com/rancher/k3s/blob/master/README.md
- MicroK8s: https://github.com/ubuntu/microk8s

We should be able to run those within Github Actions
