### ISSUE TITLE
Build a validation only mode

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#270]
**Describe the feature**
Connaisseur works as a mutating admission controller and thus replaces tags by signed digest. This also means that requests are modified. A validation only mode would simply check whether images comply with the policy (e.g. only referenced by signed digests or excluded) but fail if the a reference would require mutation.

**Optional: Is your feature request related to a problem? Please describe.**
It was reported that some enterprises are uneasy with implementing a mutating admission controller. (Might be publicly hinted though not explicit [in this blog post](https://medium.com/microsoftazure/validating-content-trust-metadata-for-kubernetes-targeted-container-images-at-deployment-time-360cafc33ef4)).

**Optional: Implementation ideas**
One could implement Connaisseur as a validating admission controller and simply deny, in case a digest is invalid or mutation  is required.

**Optional: Additional context**
As a bonus, the validation mode could also be enabled with mutation mode in parallel. As validating controllers run after mutating, this would ensure no other AC introduced an insecure image.

**Comment by xopham** [comment]
this may be required for some closed loop deployment technologies whereby for example an operator handles deployment by monitoring a git repo with configuration and comparing that to the deployed state. Such technology may detect a deviation between desired and deployed state and re-deploy which creates an infinite deployment loop

**Comment by xopham** [comment]
A first version is built by which Connaisseur will simply skip modifying the image reference.

Demo branch with Connaisseur test image (hosted in my private repository) available on branch [`demo/validation-only-mode`](https://github.com/sse-secure-systems/connaisseur/tree/demo/validation-only-mode).
To test, checkout the branch, install Connaisseur and test. To check the image references you might use `kubectl describe pods <your-test-pod>` and check for image and image ID. Further information is available [in the respective docs](https://github.com/sse-secure-systems/connaisseur/blob/demo/validation-only-mode/docs/features/validation_mode.md).

Please share your feedback :pray:

**Comment by phbelitz** [comment]
a validation mode exists in the go variant, see [docs](https://sse-secure-systems.github.io/connaisseur/latest/basics/#configuration-options_2).
