### ISSUE TITLE
Support for connaisseur to authenticate to private registries to retrieve signatures.

### ISSUE THREAD

**Issue by QWERTY92009** [sse-secure-systems/connaisseur#304]
My company is running a private artifactory registry, and we are experimenting using cosign to provide the attestation, which has worked to place the signatures in the applicable registry / repo. However, connaisseur doesn't seem to have a configuration to allow it to authenticate to the registry, resulting in this error:

`Error from server: error when creating "beamman-deployment.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Unexpected Cosign exception for image "warp10-secdev-dev.docker.artifactory.stavia.com/fake-bibb/fake-bibb:latest": error: GET https://warp10-secdev-dev.docker.artifactory.stavia.com/v2/fake-bibb/fake-bibb/manifests/latest: UNAUTHORIZED: The client does not have permission for manifest; map[manifest:fake-bibb/fake-bibb/latest/manifest.json]`

If this capability already exists, please let me know. And thanks, really enjoy working with connaisseur.

**Comment by xopham** [comment]
@QWERTY92009 Thanks for the feedback :pray: Keeps us rolling!
Does look like an authentication issue indeed. Did you use Cosign locally? Per default, it makes use of the `~/.docker/config.json` for authentication and can thus simply implement the standard docker auth.
For Connaisseur, you will have to provide a `config.json` (could be the same or a slimmed down version) as a k8s secret. That is detailed in the docs: https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/sigstore_cosign/#authentication

Let me know if that helps :slightly_smiling_face:

**Comment by QWERTY92009** [comment]
@xopham Thanks for your helpful description, which allowed me to connect the dots to the auth: configuration in values.yaml.
Works fine now, great job!
