### ISSUE TITLE
Connaisseur+cosign on Eks + ECR - Secret expiration

### ISSUE THREAD

**Issue by diegonicacio** [sse-secure-systems/connaisseur#352]
k8s version: 1.20
flavor: eks

I'm trying to run connaisseur with cosign on EKS pulling/reviewing images from ECR on the same aws account, as well as ECR on another aws accounts. Both my eks and my node group has the required IAM policies attached to them (that allows the EKS read-only access to the ECR registry). Without connaisseur everything is working fine.

The main issue is that connaisseur needs the secret to access ECR, and aws-cli generates a secret with 12-hour expiration time.
So is there any workaround to make this work on EKS + ECR scenario ?

**Comment by xopham** [comment]
@diegonicacio thanks for letting us know and sharing your workaround :pray: awesome help :rocket: 

In fact, we decided to call the keys `trust_roots` as we expected multiple formats when we released v2.0. We'll look into it and implement a feature in upcoming releases. Will be tracked under #325
