### ISSUE TITLE
Move SecurityContext to pod-level or apply on both container- as well as pod-level

### ISSUE THREAD

**Issue by annekebr** [sse-secure-systems/connaisseur#383]
**Describe the feature**
If moving the SecurityContext to pod-level, it would apply to all potential containers in the Connaisseur pod by default (could still be overwritten by SecContext on container-level)

**Optional: Is your feature request related to a problem? Please describe.**
No

**Optional: Implementation ideas**
Move or apply in both places. Think about compatibility.

**Optional: Additional context**
None

**Comment by phbelitz** [comment]
there is a `podSecurityContext` field that can be configured in the `values.yaml`
