### ISSUE TITLE
Move connytest images into same docker repo as connaisseur

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#41]
**Describe the feature**
Currently, the test images are hosted on docker.io/connytest/testimage. These should be moved into docker.io/securesystemsengineering/connaisseur or docker.io/securesystemsengineering/connytest

**Optional: Is your feature request related to a problem? Please describe.**
Would be more consistent than having a separate repo. However, makes the path much longer. 

**Optional: Additional context**
Would require quite some changes and techincally also an update of the demo gif.

**Comment by Starkteetje** [comment]
Note that the integration test also references these images

**Comment by Starkteetje** [comment]
Should also be done for the references in unittests, i.e. https://github.com/sse-secure-systems/connaisseur/blob/master/connaisseur/tests/test_mutate.py#L17 even though they may not actually be pulled at this point in time
