### ISSUE TITLE
[Elastic Common Schema] Alert Template for Elastic SIEM

### ISSUE THREAD

**Issue by operatorequals** [sse-secure-systems/connaisseur#426]
**Describe the feature**
Where I work we use the Elastic SIEM and gather all Security Events in there. As we consider denying a Container Image a serious event (as the CI/CD pipeline only works with signed images - denying means manual tampering), we need to ingest it into the SIEM so we can keep record of the following:
- Time of the event
- Cluster
- Namespace
- Image URL that was tried
- Hopefully Kubernetes user that tried the deployment

To add this feature to our stack, I created an Alert Template that follows the ECS [1]. This produces a JSON POST request
directly consumable by all HTTP/S log collector plugins [2][3], so the logs end up in an Elasticseach index (or wherever).

Finally, that format is very useful as SIEM Rules [5] can be created to optionally deliver alerts to Slack, or end up in Incident Response tools, using Kibana Integrations or Praeco integrations [4].

----

I will create another Issue for addition of Kubernetes ServiceAccount in the alert context [6], as well as the single-word messages (such as `allow`, `deny` to be used in appropriate places in the Schema [7])

[1] : https://www.elastic.co/guide/en/ecs/1.12/index.html
[2] : https://docs.fluentd.org/input/http
[3] : https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html
[4] : https://github.com/johnsusek/praeco
[5] : https://github.com/elastic/detection-rules
[6] : https://github.com/sse-secure-systems/connaisseur/blob/master/connaisseur/alert.py#L89
[7] : https://www.elastic.co/guide/en/ecs/1.12/ecs-event.html#field-event-type

**Comment by xopham** [comment]
@operatorequals this issue has been resolved by releasing #427 , right?

**Comment by operatorequals** [comment]
Yes indeed!
