### ISSUE TITLE
Expose Configuration File paths as Environment Variables

### ISSUE THREAD

**Issue by operatorequals** [sse-secure-systems/connaisseur#435]
**Describe the feature**

Add Environment Variables that designate where the Config files are mount in the filesystem.

**Optional: Is your feature request related to a problem? Please describe.**

When integrating Connaisseur with Hashicorp Vault through Pod annotations [1], I found out that there isn't a way to add Public Keys from Vault directly to the configuration, as Vault integration has a very tight way of only exporting Secrets to files. So, while it is possible to extract a templated configuration with Vault Keys to a Pod, it is impossible to point Connaisseur to that configuration file.

Having some Environment Variables that point to the Configuration files would enable Vault integration.

**Optional: Implementation ideas**
The filepaths where the Python app will find the configuration files are hardcoded [2]. They can be changed to be populated by Env Vars (in case they are not empty - leave current values as sane defaults)

**Optional: Additional context**
I know that Public Keys are not secrets and can be handled in various other ways, yet what I want to achieve is the ability of the Vault agent to hot-reload the secrets to the config files, achieving automatic key rolling through deployments.

----

[1] : https://www.vaultproject.io/docs/platform/k8s/injector/annotations
[2] : https://github.com/sse-secure-systems/connaisseur/blob/master/connaisseur/config.py#L21

**Comment by xopham** [comment]
@operatorequals I like the idea. Are you using Cosign for signing your images? In that case, it is actually possible to specify a kms link such as described here for the integration of the Connaisseur feature for Cosign: https://sse-secure-systems.github.io/connaisseur/v2.2.1/validators/sigstore_cosign/#kms-support

This technically just implements the Cosign URIs: https://github.com/sigstore/cosign/blob/main/KMS.md#hashicorp-vault

Can you check whether that works for you?

**Comment by operatorequals** [comment]
Beautiful!
You'll have a definitive answer one of these days as I'm into it.

**Comment by xopham** [comment]
@operatorequals issue seems to have gone stale as likely fixed. Will close the issue, feel free to re-open if the problem persists :slightly_smiling_face:
