### ISSUE TITLE
Issue with parent resource of type pod

### ISSUE THREAD

**Issue by hsuchan** [sse-secure-systems/connaisseur#513]
**Describe the bug**
Connaisseur is making invalid API calls when checking for parent resource, when the parent resource is of type pod.

**Detailed description**
We are using the kuberhealthy project (https://github.com/kuberhealthy/kuberhealthy), which is an operator for synthetic monitoring on Kubernetes. Kuberhealthy schedules checks (i.e. pods) at specified intervals, those pods run some monitoring tasks, and those pods terminate with a "Completed" status.

Checking for the parent of any of those temporary monitoring pods show:
```
kubectl get po dns-status-internal-1643848976 -n kuberhealthy -o json | jq ".metadata.ownerReferences"
[
  {
    "apiVersion": "v1",
    "kind": "Pod",
    "name": "kuberhealthy-7d47c7c9d6-m2skw",
    "uid": "f7852c4f-78bc-4573-b72b-1353104d7ba8"
  }
]
```

In connaisseur logs you will see the following entry:
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.233.0.1:443/apis/v1/namespaces/kuberhealthy/pods/kuberhealthy-7d47c7c9d6-m2skw
```

This error comes from:
https://github.com/sse-secure-systems/connaisseur/blob/eaa16437426d1dab5335d995ed952bf13d46acfa/connaisseur/workload_object.py#L61-L62

However this is not a valid API call.
```
curl -s $APISERVER/apis/v1 --header "Authorization: Bearer $TOKEN" --cacert /tmp/ca.crt
404 page not found
```

My EKS 1.21 cluster shows the following api-resources:

```
pods                              po                       v1                                          true         Pod
replicationcontrollers            rc                       v1                                          true         ReplicationController
daemonsets                        ds                       apps/v1                                     true         DaemonSet
deployments                       deploy                   apps/v1                                     true         Deployment
replicasets                       rs                       apps/v1                                     true         ReplicaSet
statefulsets                      sts                      apps/v1                                     true         StatefulSet
cronjobs                          cj                       batch/v1beta1                               true         CronJob
jobs                                                       batch/v1                                    true         Job
```
RestAPI calls targeting the `v1` apiVersion (core group) typically use `https://$APISERVER/api/...` instead of `https://$APISERVER/apis/...`

I suspect the same error impacts replicationcontrollers objects.

**Comment by xopham** [comment]
Closing issue as it has been resolved by PR #514 . Feel free to re-open if that is not the case.
