### ISSUE TITLE
Unable to read manifest using the same API key that works for deploying the image

### ISSUE THREAD

**Issue by QWERTY92009** [sse-secure-systems/connaisseur#533]
**Describe the bug**
We have a policy configured in values.yaml that matches the image, and a validator for that policy containing the public key corresponding to the private signing key.
Image signed by cosign.

Error:

Error from server: error when creating "image.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Unexpected Cosign exception for image "registry.docker.artifactory.xxx.com/repo/image:0.152.2-20220208T143249Z.master": Error: GET https://registry.docker.artifactory.xxx.com/v2/repo/image/manifests/0.152.2-20220208T143249Z.master: UNAUTHORIZED: The client does not have permission for manifest; map[manifest:repo/image/0.152.2-20220208T143249Z.master/manifest.json]
main.go:46: error during command execution: GET https://registry.docker.artifactory.xxx.com/v2/repo/image/manifests/0.152.2-20220208T143249Z.master: UNAUTHORIZED: The client does not have permission for manifest; map[manifest:repo/image/0.152.2-20220208T143249Z.master/manifest.json]

Note that the image deployment imagePullSecret is the same as the secret configured in values.yaml.
The secret for connaisseur was created per https://sse-secure-systems.github.io/connaisseur/v2.1.2/validators/sigstore_cosign/#authentication and is referenced for each validator as:
  auth:
    secret_name: myregistrykey

**Expected behavior**

The signed image is pulled successfully.

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>

**Optional: Versions (please complete the following information as relevant):**
 - OS: <OS and version>
 - Kubernetes Cluster: v1.19
 - Notary Server: N/A
 - Container registry: JFrog Artifactory Enterprise Plus 7.19
 - Connaisseur:  securesystemsengineering/connaisseur:v2.4.1
 - Other: <other relevant tools and versions>

**Optional: Additional context**
<Add any other context or screenshots about the bug here.>

**Comment by xopham** [comment]
@QWERTY92009 that is indeed surprising. I have tested with jfrog artifactory in the past without problems. It should be either a problem with the secret or Cosign itself.
Could you test whether you can verify with local cosign using the creds above?

**Comment by QWERTY92009** [comment]
Hi @xopham. Good tip. I cannot verify with the local cosign.

But at the same time, I *can* sign the image, telling me cosign has read access (to pull an image) and write access (to write the signature).

I'll contact our artifactory team. Thanks again, this is clearly the heart of the issue.

**Comment by QWERTY92009** [comment]
Hi @xopham. Our CI/CD pipeline apps team tells me the correct URL for the manifest is: 
https://artifactory.sativa.com:443/artifactory/registry/repo/image/0.152.2-20220208T143249Z.master/manifest.json
or
registry/repo/image/0.152.2-20220208T143249Z.master/manifest.json

cosign is apparently trying to access it at 
https://registry.artifactory.sativa.com/v2/repo/image/manifests/0.152.2-20220208T143249Z.master

Maybe there has been a jfrog API change?

**Comment by xopham** [comment]
@QWERTY92009 thanks for sharing :pray: 
It would seem that `cosign` is working according to OCI *[distribution-spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints)*: `v2/<name>/manifests/<reference>`. However, the `cosign` [docs](https://docs.sigstore.dev/cosign/registry_support) list JFROG Artifactory under supported registries. So that is a bit surprising.

**Comment by xopham** [comment]
So, [docker v2 api spec](https://docs.docker.com/registry/spec/api/#manifest) agrees with `cosign`, so I would lean towards your registry running on docker v1 api spec maybe: https://www.jfrog.com/confluence/display/JFROG/Using+Docker+V1 :shrug:

**Comment by QWERTY92009** [comment]
Excellent advice. Thanks @xopham!

**Comment by xopham** [comment]
Please let me know in case this has been resolved 🙏 Would close this, as it seems unrelated to Connaisseur. Feel free to reopen if that turns out to be falls 😊
