### ISSUE TITLE
When attempting to deploy, connaisseur errs on illegal base64 data for config.json secret_name

### ISSUE THREAD

**Issue by QWERTY92009** [sse-secure-systems/connaisseur#546]
**Describe the bug**

Command: 
kubectl apply -f deployment.yaml

Response;
Error from server: error when creating "deployment.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Unexpected Cosign exception for image "registry.docker.artifactory.sativa.com/repo/deployment:0.152.2-20220208T143249Z.master": Error: /app/connaisseur-config/app-team-val/.docker/config.json: illegal base64 data at input byte 72
main.go:46: error during command execution: /app/connaisseur-config/app-team-val/.docker/config.json: illegal base64 data at input byte 72

- The same registry secret is used in the app namespace and connaisseur namespace.
- When base64 decoded, that secret matches the docker config.json which successfully authenticates to the registry. 
- This secret was added using kubectl which base64 encoded the secret.
- However, the docker config.json is using the artifactory API key rather than basic auth (password) so is longer than a typical config.json.

**Expected behavior**
Expect connaisseur to validate the image as the image is signed.

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>

**Optional: Versions (please complete the following information as relevant):**
 - OS: Ubuntu 18.04
 - Kubernetes Cluster: Kubernetes v1.21 (GKE)
 - Notary Server: N/A
 - Container registry: Artifactory Enterprise Plus 7.19.12 
 - Connaisseur: cloned 2/8/2022.
 - Other: <other relevant tools and versions>

**Optional: Additional context**
<Add any other context or screenshots about the bug here.>

**Comment by xopham** [comment]
Closed as problem sewms resolved
