### ISSUE TITLE
Support for Nexus 

### ISSUE THREAD

**Issue by gilaiz** [sse-secure-systems/connaisseur#6]
I am using Nexus instead of Harbor this means that when I am trying to pull an image the command will look like this:
"pull nexus.example.com:18079/hello-world:test"
I am getting the following error:
Error from server: admission webhook "connaisseur-svc.connaisseur.svc" denied the request: "nexus.example.com:18079/hello-world:test" is not a valid image format. 
from what I understand the problem is with the validation of the path format. Is there a way to make Connaisseur work with Nexus?

**Comment by annekebr** [comment]
Thanks a lot for your feedback! We try to keep Connaisseur as compatible as we possible, so such tests in other platforms help a lot!

It seems that the regex used for the [image name validation](https://github.com/sse-secure-systems/connaisseur/blob/2b4e5314d1a11174a069cf1e6345952af3162b26/connaisseur/image.py#L30) does currently not allow ports. We are working on an MR to fix the image validation and will make an update soon!

**Comment by gilaiz** [comment]
Thank you for the update.
Do you know when the update will be available? this is very urgent.

**Comment by annekebr** [comment]
I pushed a proposed fix that is neither fully tested nor fully reviewed yet. This will be merged monday at the earliest. 

If you want to test it in advance, you should be able to test it by pulling the `fix-image-validation` branch, building and pushing the new test docker image to your registry, changing the kubectl pull secret to point to your own registry and changing the reference [https://github.com/sse-secure-systems/connaisseur/blob/fix-image-validation/helm/values.yaml#L4](here).

We'd appreciate your feedback if it works before we can test ourselves!

**Comment by annekebr** [comment]
Hey @gilaiz! We merged the proposed fix and the input validation should allow a custom port for your nexus registry by now. 

Feel free to reopen in case you face any issues!
