### ISSUE TITLE
Please allow a values.yaml entry for notary port

### ISSUE THREAD

**Issue by perezjasonr** [sse-secure-systems/connaisseur#62]
**Describe the feature**
Along with the host, I think it would be nice to be able to specify the port.

**Optional: Is your feature request related to a problem? Please describe.**
Yes. By default, if you do your own notary, which I think a big reason many people will be looking to this the port will not always be 443, for example the demo I'm following it uses 4443:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='notary-server-svc.notary.svc', port=443): Max retries exceeded with url: /_notary_server/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe50813f4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

I was able to specify the host but not the port.

**Optional: Implementation ideas**
Simply have an entry in the helm values file for notary.port (or something similar)

**Optional: Additional context**
If possible is there a place I can change in the meantime to force the port to be 4443 (or another port?) outside of the values file? could be a nice workaround

**Comment by phbelitz** [comment]
Hey thank you for the issue. You should be able to just append the port to the hostname in the `values.yaml`. Like this:

```yaml
notary:
    host: notary.docker.io:4443
```

Should this doesn't solve the issue, feel free to ask back and we'll take a closer look. Cheers.

**Comment by perezjasonr** [comment]
Thank you! that appears to have worked and it came up and didnt complain about reaching notary.
I guess port being a separate entry in values.yaml for clusterIP (and in other values files in other charts) brainwashed me into thinking port must be its own value entry.
