### ISSUE TITLE
GitHub Container Registry for CI

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#624]
**Describe the feature**
GitHub offers the [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) (ghcr) for container images (private and public). This can be used within the CI to store images.

**Optional: Is your feature request related to a problem? Please describe.**
Using a container registry is a more native approach to pass images between different CI steps and can simplify testing and publication.

**Optional: Implementation ideas**
* prepare more re-usable actions
* [security harden github actions](https://docs.github.com/en/github-ae@latest/actions/security-guides/security-hardening-for-github-actions)
* use BuildKit/Buildx to speed up building
* use GITHUB_TOKEN and only-read tokens for security during testing (e.g. imagePullSecrets)
* sign/verify using cosign
* build branch images (master, tag, dev, <any-branch>), however make sure to not create image confusion (digest for reference)
* inject connaisseur image reference, validator and policy into `helm/values.yaml` to declutter testing
* potentially provide release candidates or dev builds
* check storage limits
* ensure frequent cleanup (on branch merge, as cron)

Please add further ideas below!

**Comment by phbelitz** [comment]
already implemented.
