### ISSUE TITLE
Rework error message handling

### ISSUE THREAD

**Issue by phbelitz** [sse-secure-systems/connaisseur#646]
**Describe the feature**
Currently the error messages are templates that are filled upon initialization with context variables. This is a not intended behavior, since additional context data, which gets introduced when catching the error, is being ignored. Fixing this also gives the opportunity to generally reqork the error messages. 

Goal is to have:
- meaningful error messages
- errors should include context information
- context information should not be overwritable

**Comment by Starkteetje** [comment]
Expanding onto:
- context information should not be overwritable

Not sure, whether this is actually what we want. However, we either want them to not be overwritable as the context set by a lower-level function usually knows more specifics, but it may also be the case, that we'd want that for some reason. If so, we need to make sure that iff a function does know exactly which error message it wants to raise, that said message is rendered prior to the higher-level context changes.

**Comment by phbelitz** [comment]
error messages in golang are currently good enough, so no longer an issue. closing.
