### ISSUE TITLE
Kubernetes Sigstore support as of v1.24

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#651]
**Describe the feature**
Kubernetes introduced [Sigstore support as of v1.24](https://blog.sigstore.dev/kubernetes-signals-massive-adoption-of-sigstore-for-protecting-open-source-ecosystem-73a6757da73). It should be considered how that can be used within Connaisseur, e.g. validating k8s signatures, and what additional consequences derive.

**Comment by xopham** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-images/

**Comment by phbelitz** [comment]
because of a lack of knowledge on what to do here, i am closing this issue 🤷
