### ISSUE TITLE
Connaisseur can not be deployed to other namespace 

### ISSUE THREAD

**Issue by hhyeh** [sse-secure-systems/connaisseur#724]
**Describe the bug**
When using helm install connaisseur connaisseur/connaisseur --atomic --create-namespace --namespace security

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Optional: To reproduce**
NAME: connaisseur

LAST DEPLOYED: Sun Oct 17 14:39:58 2021
NAMESPACE: connaisseur
STATUS: deployed
REVISION: 1
TEST SUITE: None

**Optional: Versions (please complete the following information as relevant):**
 - OS: Ubuntu 18.04.1 LTS
 - Kubernetes Cluster: gcloud  k8 version
 - Notary Server: Notary.io v1
 - Container registry: docker 20.1010
 - Connaisseur: 1.2.2
 - Other: <other relevant tools and versions>

**Optional: Additional context**
Error: INSTALLATION FAILED: template: connaisseur/templates/certificate_webhook-conf.yaml:17:46: executing "connaisseur/templates/certificate_webhook-conf.yaml" at <include "getInstalledTLSCert" .>: error calling include: template: connaisseur/templates/_helpers.tpl:130:14: executing "getInstalledTLSCert" at <lookup "v1" "Secret" "connaisseur" (printf "%s-tls" .Chart.Name)>: error calling lookup: secrets "connaisseur-tls" is forbidden: User "xyz1" cannot get resource "secrets" in API group "" in the namespace "connaisseur"

it is not a permission issue on the user but rather, the conniasseur is looking to specially connaisseur. even when the namespace was specified to xyz.

**Comment by Starkteetje** [comment]
Hi @hhyeh 
thanks for reporting and diagnosing this issue. I'll hopefully fix this today and then the fix will make it's way into the next release.
