### ISSUE TITLE
Error logs do not contain image information, only pod name

### ISSUE THREAD

**Issue by richgerrard** [sse-secure-systems/connaisseur#811]
**Describe the feature**
Error logs contain the image that was denied, not just the pod name/id

**Optional: Is your feature request related to a problem? Please describe.**
It should be.  images > pod ids in this context.

**Optional: Implementation ideas**
Here's the idea, instead of:
```ERROR: {'message': 'Static deny.', 'context': {'detection_mode': True, 'user': 'admin', 'operation': 'CREATE', 'kind': 'Pod', 'name': 'nsenter-n6exa6', 'namespace': 'default'}}```
We try this:
```ERROR: {'message': 'Static deny.', 'context': {'detection_mode': True, 'user': 'admin', 'operation': 'CREATE', 'kind': 'Pod', 'name': 'nsenter-n6exa6', 'namespace': 'default', 'image': 'relevantinformation:tag@sha:blahblah}}```

**Optional: Additional context**
N/A

**Comment by Starkteetje** [comment]
Hi @richgerrard
that's a good idea. At least for the Notary validator this was the case already, but for static it isn't. I'll check for Cosign as well and will implement a fix
