### ISSUE TITLE
Document delegations feature

### ISSUE THREAD

**Issue by Starkteetje** [sse-secure-systems/connaisseur#87]
We have this nice feature of being able to require delegations for specific images. Yet, this feature gets promoted in a single sentence in the README and doesn't have documentation (outside code and tests). We should add some. Maybe ADVANCED_USECASES.md or the likes?

**Comment by eumel8** [comment]
@Starkteetje thx for the commit so far which explains the delegations feature in values.yaml. 
Unfortunatelly since I've added delegation to my repo where I want to verify docker trust, I got error message:

`admission webhook "connaisseur-svc.connaisseur.svc" denied the request: trust data has invalid format.`

Without delegation the validation works fine with  admission controller

**Comment by Starkteetje** [comment]
Did you sign with the correct key? If you run `docker trust inspect $YOURIMAGENAMEANDPATH` (assuming you use DockerHub), is the tag signed with the key you specified in the `helm.yalues.yaml`?

**Comment by eumel8** [comment]
@Starkteetje yes, I put the public root key in helm.values.yaml and sign an image. The repo looks like that: 

```
$ DOCKER_CONTENT_TRUST_SERVER=https://notary.external.otc.telekomcloud.com DOCKER_CONTENT_TRUST=1 docker trust inspect --pretty  mtr.external.otc.telekomcloud.com/eumel8/gnuu

Signatures for mtr.external.otc.telekomcloud.com/eumel8/gnuu

SIGNED TAG          DIGEST                                                             SIGNERS
0.0.1               167f4a58603f169eac4e024f853cc117abe6603f59f16ea42ffb5db1ada44db9   eumel8

List of signers and their keys for mtr.external.otc.telekomcloud.com/eumel8/gnuu

SIGNER              KEYS
eumel8              88ca03e36ea0

Administrative keys for mtr.external.otc.telekomcloud.com/eumel8/gnuu

  Repository Key:       4f6aa580f0a5304e45ae8cee395bac929ccc18c148a909f535e37c86d113bd4f
  Root Key:     d7ce4144ecfa9f934b3770b8a545f73cba10176346de6e3b9eeeead80864f15a
```

When I deploy the image on a cluster, the verification works sucessful:

```
successful verification of image "mtr.external.otc.telekomcloud.com/eumel8/gnuu@sha256:167f4a58603f169eac4e024f853cc117abe6603f59f16ea42ffb5db1ada44db9"
```

Then I generate a new cert and add another user for delegation.:

```
$ notary -s https://notary.external.otc.telekomcloud.com -d ~/.docker/trust delegation add  --all-paths   mtr.external.otc.telekomcloud.com/eumel8/gnuu targets/hiller delegation.crt -p
```

Then the repo looks like that: 

```
$ DOCKER_CONTENT_TRUST_SERVER=https://notary.external.otc.telekomcloud.com DOCKER_CONTENT_TRUST=1 docker trust inspect --pretty  mtr.external.otc.telekomcloud.com/eumel8/gnuu

Signatures for mtr.external.otc.telekomcloud.com/eumel8/gnuu

SIGNED TAG          DIGEST                                                             SIGNERS
0.0.1               167f4a58603f169eac4e024f853cc117abe6603f59f16ea42ffb5db1ada44db9   eumel8

List of signers and their keys for mtr.external.otc.telekomcloud.com/eumel8/gnuu

SIGNER              KEYS
eumel8              88ca03e36ea0
hiller              97471508954b

Administrative keys for mtr.external.otc.telekomcloud.com/eumel8/gnuu

  Repository Key:       4f6aa580f0a5304e45ae8cee395bac929ccc18c148a909f535e37c86d113bd4f
  Root Key:     d7ce4144ecfa9f934b3770b8a545f73cba10176346de6e3b9eeeead80864f15a
```

Now when I try to apply the same image to the cluster I get an error: 

```
admission webhook "connaisseur-svc.connaisseur.svc" denied the request: trust data has invalid format.
```

Not sure if this is an error due the multiple keys by delegation or an mistake by me while I read the documentation.

Notary service is based on latest release of https://github.com/theupdateframework/notary.

**Comment by Starkteetje** [comment]
@eumel8 Is the key you're adding an ECDSA key? Notary supports more key types than Connaisseur (see also #99 ). As my colleague mentioned on the ticket, we didn't anticipate many people to use the delegations feature (in addition to it having basically no documentation) and the default DCT keys are ECDSA

If you're using ECDSA keys, the validation seems to fail [here](https://github.com/sse-secure-systems/connaisseur/blob/master/connaisseur/trust_data.py#L63), so the JSON is not accepted by our schema. If you could paste a (potentially redacted) copy of the trust data, we might be better able to help you (I saw you removed the hiller trust data, so I can't see what made yours fail)

**Comment by eumel8** [comment]
@Starkteetje Okay, thanks. I think it works now as expected. I generated the hiller key with this openssl commands, which obviously not work: 

```
openssl req -new -sha256 -key delegation.key -out delegation.csr
openssl x509 -req -sha256 -days 365 -in delegation.csr -signkey delegation.key -out delegation.crt
```
When I generate in a second account the key with docker cli `docker trust key generate hiller`  and import the created public key in the account with the root key:

```
notary -s https://notary.external.otc.telekomcloud.com -d ~/.docker/trust delegation add  --all-paths -p  mtr.external.otc.telekomcloud.com/eumel8/gnuu targets/hiller hiller-pub.key  -p
```

it works like a charm. I wasn't aware that there are different key allgorithm and how to check which type is on place.
