### ISSUE TITLE
Choose most recent digest for tag with multiple signatures

### ISSUE THREAD

**Issue by Starkteetje** [sse-secure-systems/connaisseur#91]
**Describe the feature**
If multiple signers sign the same tag, but for different digests (and not both of them are required as per image policy), Connaisseur should be able to choose the latest signed digest via `release.json`

**Optional: Additional context**
Probably needs subsequent changes to validation documentation as well

**Comment by phbelitz** [comment]
This should already be the case. If there are no required delegations, Connaisseur will take the `targets/releases` should there be delegations defined.
