### ISSUE TITLE
Support Cosign 2.0

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#918]
**Describe the feature**
[Cosign 2.0 was released](https://github.com/sigstore/cosign/releases/tag/v2.0.0) and contains [many breaking changes](https://blog.sigstore.dev/cosign-2-0-released/). This will need adaption.

**Optional: Is your feature request related to a problem? Please describe.**
Verification of cosign 2.0 signatures may not be compatible anymore. Would need to be checked for release. This may end up being breaking to some extend, potentially require additional flags, such as optional `--insecure-ignore-tlog=true`. Consider this carefully.

**Comment by peterthomassen** [comment]
You probably know this already, but there's now a Python implementation you might want to leverage: https://pypi.org/project/sigstore/

**Comment by xopham** [comment]
Yes, but you are right that this may be a good moment to try the switch.

I believe the package is centrally aimed towards signing python packages not container images and there may be a lot to workt around for the OCI registry interface.
Still, we should try as this might be more natural and less hacky :rocket:

**Comment by xopham** [comment]
fixed
