### ISSUE TITLE
Update Connaisseur logs to JSON format

### ISSUE THREAD

**Issue by shani-e** [sse-secure-systems/connaisseur#976]
Currently, Connaisseur logs are written in a string format. 

However, most log collection systems require logs to be in JSON format. This is a common standard that is widely supported.

Therefore, we propose that the Connaisseur logs be updated to JSON format. 

This can be done by modifying the logging configuration in the Connaisseur code to output logs in JSON format. 

Alternatively, a boolean variable could be added to the values file that would allow users to control the output format of the logs.

Updating Connaisseur logs to JSON format would make it easier for users to collect and analyze logs using popular log collection tools.

 It would also align Connaisseur with industry best practices for logging.

I believe that this feature would be a valuable addition to Connaisseur and would greatly improve its usability.

Instead of:
```
[2023-03-28 09:34:19,297] INFO: COSIGN output of trust root 'current' for image'registry.com/shani/shani-tests:test': RETURNCODE: 0; STDOUT: {"critical":{"identity":{"docker-reference":"registry.com/shani/shani-tests"},"image":{"docker-manifest-digest":"sha256:6b7c4a1779437c9815b021e914eadad759b0c38842b17aef7f710f66"},"type":"cosign container image signature"},"optional":null}

```

to be like:
```
{"timestamp": "2023-03-28T09:34:19.297Z", "level": "INFO", "message": "COSIGN output of trust root 'current' for image 'registry.com/shani/shani-tests:test'", "returncode": 0, "stdout": {"critical": {"identity": {"docker-reference": "registry.com/shani/shani-tests"}, "image": {"docker-manifest-digest": "sha256:6b7c4a1779437c9815b021e914eadad759b0c38842b17aef7f710f66"}, "type": "cosign container image signature"}, "optional": null}}

```

**Comment by Starkteetje** [comment]
Hi @shani-e 
that's a good idea and we can certainly make it work with a config flag. Given we have a planned release of Connaisseur 3 with breaking changes, we might take the opportunity to even switch to JSON logging as the default, but not making any promises there.
